version: '2.4'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    env_file:
      - ./.env-mongo
    volumes:
      - db-data:/data/db

  backend:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  db-data:
